<<<<<<< HEAD
name: Mon_Workflow
=======
name: CI/CD Pipeline
>>>>>>> 81ac526727d48d178446807574c1ec2904e1eea6

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

<<<<<<< HEAD
      - name: Utilisation d'une image Docker
        uses: docker://ubuntu:latest  # Remplacez ici par l'image Docker que vous souhaitez utiliser
        with:
          args: echo "Exécution de quelque chose dans le conteneur Docker"
=======
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: path/to/your/files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 81ac526727d48d178446807574c1ec2904e1eea6
